apiVersion: v1
kind: Service
metadata:
    name: samudralajeevanalakshmijeevanauserservice
spec:
    type: LoadBalancer
    ports:
    - port: 8082 
    selector:
        app: samudralajeevanalakshmijeevanauserservice